services:
  private-gpt:
    image: privategpt
    build:
      context: .
      # context: https://github.com/zylon-ai/private-gpt.git#main
      args:
        - POETRY_EXTRAS=vector-stores-qdrant llms-ollama embeddings-ollama embeddings-huggingface
    volumes:
      - ./local_data/:/home/worker/app/local_data
    ports:
      - 8001:8080
    environment:
      PORT: 8080
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
    ## Nvidia  GPU support ##
    # runtime: nvidia
    # ipc: host
    # devices:
    #   - nvidia.com/gpu=0
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ./models:/root/.ollama
